# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spmia?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: hankai
    password: Kevin1808
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    open-in-view: true
